// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvOCyO4M2x4saDAwZiTy3FKxZ6-KZ2Wl0',
    appId: '1:195053807922:web:f12548bf577c1accc78f2b',
    messagingSenderId: '195053807922',
    projectId: 'venicego-app',
    authDomain: 'venicego-app.firebaseapp.com',
    databaseURL: 'https://venicego-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'venicego-app.appspot.com',
    measurementId: 'G-NSQDR7EFNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0g4P0T8ytXo3T6AI-uEUOCxNPWimEAts',
    appId: '1:195053807922:android:ada27c2cd163918ec78f2b',
    messagingSenderId: '195053807922',
    projectId: 'venicego-app',
    databaseURL: 'https://venicego-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'venicego-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLA4ZUtNt-OTqeyvzEIXMyTg1kAI8Nn04',
    appId: '1:195053807922:ios:b9c8bcc2da0a1718c78f2b',
    messagingSenderId: '195053807922',
    projectId: 'venicego-app',
    databaseURL: 'https://venicego-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'venicego-app.appspot.com',
    iosBundleId: 'unive.it.veniceGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLA4ZUtNt-OTqeyvzEIXMyTg1kAI8Nn04',
    appId: '1:195053807922:ios:c7dadde0e4d069c8c78f2b',
    messagingSenderId: '195053807922',
    projectId: 'venicego-app',
    databaseURL: 'https://venicego-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'venicego-app.appspot.com',
    iosBundleId: 'unive.it.veniceGo.RunnerTests',
  );
}
